### ISSUE TITLE
Problem in comparing nested arrays

### ISSUE THREAD

**Issue by Romick2005** [deepu105/angular-object-diff#1]
Please try to compare
{
   "a": [
     "b: 1"
   ],
  "documents": [
       {
           "fileFormat": "pdf"
        }
    ]
 }
and
{
   "a": [
     "b: 3"
   ],
  "documents": [
       {
           "fileFormat": "pdf"
        }
    ]
 }

Results:
{
a: {
0: "b: 1",
0: "b: 3"
{,
documents: {
0: {
fileFormat: "pdf"
},
0: {
fileFormat: "pdf"
}
{
{

Expected results :
1) Documents array should be marked as unchanged
2) Array representation should also be unchanged( object notation {0 : } instead : [...])
3) Wrong closing brackets } instead of {.
![image](https://cloud.githubusercontent.com/assets/17779660/13697170/d0b8e59c-e76b-11e5-9f60-8b5e4999eb43.png)

**Comment by deepu105** [comment]
Seems like an issue, will see what I can do

**Comment by deepu105** [comment]
fixed via https://github.com/hipster-labs/angular-object-diff/commit/4299d0680d2aa276ab52cc7e3654df8b2689c521

The array representation to object representation is a minor issue but array is just another hash anyway. fixing that would be bit of a work so may be a feature for future versions

**Comment by deepu105** [comment]
In a way its a feature so that even array position changes are highlighted correctly

**Comment by Romick2005** [comment]
Can you please review my fixes and merge them into master?
https://github.com/Romick2005/angular-object-diff/branches

**Comment by deepu105** [comment]
I have already fixed it can you check

**Comment by Romick2005** [comment]
Hi almost all is covered except  of correct own property implementation.
I would expect that own check also applies to object "a" not only for object "b".
if (isOwn && !a.hasOwnProperty(key)) {//to skip not own properties
        continue;
}
Can you please take care of that too?

**Comment by deepu105** [comment]
let me check

Thanks & Regards,
Deepu

**Comment by Romick2005** [comment]
Hi Deepu,

I mean :+1:
 `for (var key in a) {
                if (isOwn && !a.hasOwnProperty(key)) {//to skip not own properties
                    continue;
                }
                if ((!isOwn && key in b) || (isOwn && typeof b != 'undefined' && b.hasOwnProperty(key))) {
`
because for now you check only b object for own properties and skip a object for this check. And when you pass angular object to compare it prints all own properties.
Thanks.
