### ISSUE TITLE
getRandomItem and getRandomCollection with Arrays

### ISSUE THREAD

**Issue by xavisavvy** [deepu105/angular-object-diff#2]
Is there an option I am missing to avoid it adding or at least showing the properties created for arrays? 

![image](https://cloud.githubusercontent.com/assets/2219111/15058300/0bc5e86a-12e1-11e6-95d9-7aa4f8f5d7fa.png)

**Comment by deepu105** [comment]
Use the `diffOwnProperties` method to avoid taking prototype methods into account.

**Comment by xavisavvy** [comment]
Thank you! I figured I was just missing something.
